### ISSUE TITLE
move tab to bottom

### ISSUE THREAD

**Issue by rishabhgupta03** [Bpitorg/BPIT_Frontend#14]
the info tab needs to be moved to extreme bottom and many fields like "team" and "list of students placed" not updated.

![image](https://user-images.githubusercontent.com/44132253/85207139-775db780-b344-11ea-95f6-f4e1a5a24e44.png)

**Comment by Mayankjh** [comment]
@rishabhgupta03 The data is not populated yet on the website hence the footer appears to be moving up due to lack of content. Once the data is populated the screen would appear normal. Still, I would recommend @ChauhanRitika to add a minimum height property for each page in the main style.scss file. Thanks for identifying :)

**Comment by ChauhanRitika** [comment]
changes added
